"""<remove relationship in Season"


Revision ID: 01905cd670f5
Revises: 54fc9d33334c
Create Date: 2023-04-19 09:57:22.162461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01905cd670f5'
down_revision = '54fc9d33334c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
