"""delete foreign keys"


Revision ID: 45a00305d580
Revises: 01905cd670f5
Create Date: 2023-04-19 10:40:22.067496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a00305d580'
down_revision = '01905cd670f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'results', 'contestants', ['sixth'], ['id'])
    op.create_foreign_key(None, 'results', 'contestants', ['winner'], ['id'])
    op.create_foreign_key(None, 'results', 'contestants', ['fifth'], ['id'])
    op.create_foreign_key(None, 'results', 'contestants', ['fourth'], ['id'])
    op.create_foreign_key(None, 'results', 'contestants', ['second'], ['id'])
    op.create_foreign_key(None, 'results', 'seasons', ['season'], ['id'])
    op.create_foreign_key(None, 'results', 'contestants', ['first'], ['id'])
    op.create_foreign_key(None, 'results', 'contestants', ['third'], ['id'])
    # ### end Alembic commands ###
