"""added relationship to Season Method for results"


Revision ID: 54fc9d33334c
Revises: 3edccb29d0d5
Create Date: 2023-04-19 09:40:14.883355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54fc9d33334c'
down_revision = '3edccb29d0d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
